version: 2
updates:
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'Dobefu'
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'Dobefu'
