root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["server", "--port", "40000"]
  bin = "./app"
  cmd = "go build -ldflags=\"-s -w\" -o app"
  delay = 100
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "gohtml", "json", "css"]
  include_file = []
  kill_delay = "0s"
  log = "tmp/build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = [
    "pnpm build:css",
  ]
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = true
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 40000
  enabled = true
  proxy_port = 4000

[screen]
  clear_on_rebuild = false
  keep_scroll = true
