name: go-web-starter

services:
  db:
    image: postgres:latest
    container_name: db
    restart: on-failure
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '2345:5432'

  cache:
    image: eqalpha/keydb:latest
    container_name: cache
    restart: on-failure
    command:
      - 'keydb-server'
      - '--save'
      - ''
      - '--appendonly'
      - 'no'
    volumes:
      - cache:/data
    ports:
      - '9736:6379'
    healthcheck:
      test:
        - 'CMD'
        - 'keydb-cli'
        - 'ping'
      interval: 10s
      timeout: 3s
      retries: 3
    # --- Linux-only options below ---
    # For lowest latency on Linux, uncomment the next line:
    # network_mode: host

  mail:
    image: axllent/mailpit
    container_name: mail
    restart: on-failure
    ports:
      - '5208:8025'
      - '5201:1025'
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  spamassassin:
    image: instantlinux/spamassassin
    container_name: spamassassin
    restart: on-failure
    ports:
      - '3870:783'

volumes:
  postgres:
  cache:
