name: CI

on:
  push:
    branches: ['*']
    tags: ['v*']
  pull_request:
    branches: ['*']

permissions:
  contents: write

jobs:
  build-test:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - name: Install Go dependencies
        run: go get .

      - name: Install NodeJS dependencies
        run: pnpm install

      - name: Build the application
        run: make build

      - name: Create a test results directory
        run: mkdir test-results

      - name: Run tests
        run: |
          go test "./..." -coverprofile="test-results/coverage.out" -covermode=count
          go test "./..." -coverprofile="coverage.out" -covermode=count -json > test-report.out

      - uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: './.nvmrc'
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - name: Install NodeJS dependencies
        run: pnpm install

      - name: Run the linter
        run: pnpm lint

  sonar-scan:
    name: 'SonarQube Scan'
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
